<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="es">
<!--<![endif]-->

<head>
  <?php include("head.php"); ?>
  <link rel="stylesheet" href="<?php echo ruta ?>app/css/geofal-redesign.css">
</head>

<body>
  <!-- Left Panel -->
  <?php include("header_left.php"); ?>

  <!-- Right Panel -->
  <div id="right-panel" class="right-panel">
    <!-- Header-->
    <?php include("header_top.php"); ?>

    <!-- Breadcrumbs -->
    <div class="breadcrumbs">
      <div class="col-sm-12">
        <h1>INICIO</h1>
      </div>
    </div>

    <!-- Main Content -->
    <div class="content">
      <div class="col-sm-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <span class="badge badge-pill badge-success">Sistema</span> Gestion de empresas Geofal
        </div>
      </div>
    </div>
  </div>

  <?php include("footer.php"); ?>
</body>
</html>
