<!doctype html>

<html>



<head>



  <?php include("head.php"); ?>



</head>



<body>



  <?php include("header.php"); ?>



  <div class="container">

    <div class="row">



      <div id="rev_slider_12_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="construction-slider8" data-source="gallery" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">







        <div id="rev_slider_12_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.3.0.2.1">

          <ul>



          <li data-index="rs-37" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="<?= ruta ?>include/revolution/assets/slide5/100x50_3a82d-slide7-1.jpg" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">

              <img src="<?= ruta ?>include/revolution/assets/slide5/slider-4.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal." data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Power0.easeIn" data-scalestart="100" data-scaleend="100" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" class="rev-slidebg" data-no-retina>

            </li>



            <li data-index="rs-37" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="<?= ruta ?>include/revolution/assets/slide5/100x50_3a82d-slide7-1.jpg" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">

              <img src="<?= ruta ?>include/revolution/assets/slide5/slider-1.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal." data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Power0.easeIn" data-scalestart="100" data-scaleend="100" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" class="rev-slidebg" data-no-retina>

            </li>



            <li data-index="rs-38" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="<?= ruta ?>include/revolution/assets/slide5/100x50_3a82d-slide7-1.jpg" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">

              <img src="<?= ruta ?>include/revolution/assets/slide5/slider-2.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal." data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Power0.easeIn" data-scalestart="100" data-scaleend="100" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" class="rev-slidebg" data-no-retina>

            </li>



            <li data-index="rs-39" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="<?= ruta ?>include/revolution/assets/slide5/100x50_3a82d-slide7-1.jpg" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">

              <img src="<?= ruta ?>include/revolution/assets/slide5/slider-3.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal." data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Power0.easeIn" data-scalestart="100" data-scaleend="100" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" class="rev-slidebg" data-no-retina>

            </li>



          </ul>

          <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>

        </div>



      </div>

    </div>



  </div>



  <section class="page-section-pt pb-130" style="color: #ffffff;">



    <div class="container">

      <div class="row">



        <div class="col-sm-8 text-left">

          <div class="section-title text-left">

            <h2 class="title" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">¿Quiénes somos?</h2>

          </div>

          <p style="font-size: 16px; color: #404040;" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Somos una empresa especializada en el área de Estudio de suelos y Laboratorio de suelos, concreto, pavimento y unidades de albañilería, control de calidad en obras civiles, evaluación estructural e ingeniería. Enfocada en aportar soluciones integrales que se traduzcan en valor agregado para los proyectos de nuestros clientes. <br> <br>

            Todos nuestros procesos son constantemente monitoreados y controlados mediante metodología, criterio y software, con el principal propósito de garantizar la mejor calidad en los resultados finales entregados. </p>

            

            <br>

            

              <div class="col-sm-4"><img src="<?= ruta ?>admin/publico/img/inacal.jpg" style="height: 100px;" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal."> </div>

            

            <div class="col-sm-8" style="color: #000;"> Actualmente nos encontramos acreditados en 10 métodos de ensayo. El alcance se encuentra detallado y disponible para consulta en la web del INACAL. <a href="<?= ruta ?>include/alcance.pdf" target="_blank" style="font-weight: 600; color: red;"> VER ALCANCE </a>

            </div>

          

            

        </div>



        <div class="col-sm-4 text-center">

          <div class="section-title text-center">

          <div class="isotope popup-gallery popup-gallery">

            <div class="grid-item masdies a1">

              <div class="project-info">

                <img class="img-responsive center-block" src="<?= ruta ?>include/images/project/inacal2.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                <div class="overlay">

                  <div class="overlay-content">

                    <a href="<?= ruta ?>include/images/project/inacal2.jpg" class="button popup-img border small animated middle-fill" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                      <span>

                        <i class="fa fa-arrows-alt"></i> </span></a>

                  </div>

                </div>

              </div>

            </div>

          </div>



          </div>

          

        </div>



        <!--



        <div class="col-sm-4 text-center">

          <div class="section-title text-center">

          <img src="<?= ruta ?>include/images/project/iso.jpg" style="height: 100px;" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">



          <br> 

          <div class="isotope popup-gallery popup-gallery">

            <div class="grid-item masdies a1">

              <div class="project-info">

                <img class="img-responsive center-block" style="width: 185px;" src="<?= ruta ?>include/images/project/sgs.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                <div class="overlay">

                  <div class="overlay-content">

                    <a href="<?= ruta ?>include/images/project/sgs.jpg"  class="button popup-img border small animated middle-fill" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                      <span>

                        <i class="fa fa-arrows-alt"></i> </span></a>

                  </div>

                </div>

              </div>

            </div>

          </div>



          </div>

          

        </div>

        

        -->



      </div>

    </div>

  </section>



  <section class="page-section-ptb">

    <div class="container">

      <div class="row">

        <div class="col-sm-12">

          <div class="section-title text-center">

            <h2 class="title" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Servicios</h2>

          </div>

        </div>

        <div class="col-sm-12">

          <div class="owl-carousel" data-items="4" data-xs-items="2">

            <div class="item">

              <div class="team boxed">

                <div class="team-images"> <a href="estudio-de-suelos.php" title="Laboratorio de suelos, Concreto y Asfalto – Geofal."><img class="img-responsive" src="<?= ruta ?>include/images/team/servicio-1.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                  </a> </div>

                <div class="team-description">

                  <h4><a href="estudio-de-suelos.php" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Estudio de Suelos</a></h4>

                </div>

              </div>

            </div>

            <div class="item">

              <div class="team boxed">

                <div class="team-images"> <a href="laboratorio-de-suelo-concreto-pavimento-y-albanileria.php"> <img class="img-responsive" src="<?= ruta ?>include/images/team/servicio-2.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal."> </a> </div>

                <div class="team-description">

                  <h4><a href="laboratorio-de-suelo-concreto-pavimento-y-albanileria.php" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Laboratorio

                      de Suelo,

                      Concreto, Pavimento

                      y Albañileria</a></h4>

                </div>



              </div>

            </div>

            <div class="item">

              <div class="team boxed">

                <div class="team-images"> <a href="control-de-calidad-de-obras-civiles.php"> <img class="img-responsive" src="<?= ruta ?>include/images/team/servicio-3.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal."> </a> </div>

                <div class="team-description">

                  <h4><a href="control-de-calidad-de-obras-civiles.php" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Control de calidad de obras

                      civiles</a></h4>



                </div>

              </div>

            </div>

            <div class="item">

              <div class="team boxed">

                <div class="team-images"> <a href="evaluacion-estructural-e-ingenieria.php"> <img class="img-responsive" src="<?= ruta ?>include/images/team/servicio-4.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal."> </a> </div>

                <div class="team-description">

                  <h4><a href="evaluacion-estructural-e-ingenieria.php" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Evaluación estructural e

                      ingeniería</a></h4>

                </div>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </section>





  <section class="page-section-pt pb-50" style="background-color: #ddd9d7; color: #ffffff;">

    <div class="container">

      <div class="row">

        <div class="col-sm-1 text-center">

        </div>

        <div class="col-sm-2 text-center">

          <div class="isotope popup-gallery popup-gallery">

            <div class="grid-item masdies a1">

              <div class="project-info">

                <img class="img-responsive center-block" src="<?= ruta ?>include/images/project/politica.jpg" alt="Geofal | Geotecnica & Laboratorio" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">

                <div class="overlay">

                  <div class="overlay-content">

                    <a href="<?= ruta ?>include/images/project/politica.jpg" title="Laboratorio de suelos, Concreto y Asfalto – Geofal." class="button popup-img border small animated middle-fill">

                      <span>

                        <i class="fa fa-arrows-alt"></i> </span></a>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </div>





        <div class="col-sm-8 text-center">

          <div class="section-title text-center">

            <h2 class="title" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Política de Calidad</h2>

          </div>

          <p style="font-size: 16px; color: #404040;" title="Laboratorio de suelos, Concreto y Asfalto – Geofal.">Conscientes de nuestro compromiso con la calidad de

            nuestros

            servicios, tenemos como política asegurar la máxima satisfacción del

            cliente, cumpliendo con la normativa vigente y fomentando la

            participación de nuestros colaboradores en la mejora continua.</p>

        </div>



        <div class="col-sm-1 text-center">



        </div>



      </div>

    </div>

  </section>





  <?php include("carusel.php"); ?>





  <div class="footer-widget-1 mt-10">



  </div>







  <?php include("footer.php"); ?>

</body>



</html>